name: build_when
description: Simplify BlocBuilder's buildWhen logic with declarative filters. Automatically handles primitives, nulls, and collections. Perfect for Flutter BLoC state management.
version: 0.1.0
homepage: https://github.com/xamantra/build_when
repository: https://github.com/xamantra/build_when
documentation: https://github.com/xamantra/build_when#readme
license: MIT

environment:
  sdk: 3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1

dev_dependencies:
  lints: 6.0.0
  very_good_analysis: 10.0.0
  flutter_test:
    sdk: flutter